# Generated by Django 3.0.7 on 2021-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
