# Generated by Django 3.0.7 on 2021-01-12 08:23

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210112_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='featured_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='featured_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
